### ISSUE TITLE
Running Stratum

### ISSUE THREAD

**Issue by Qurmo** [sammy007/monero-stratum#52]
I did everything as explained in the tutorial, but at the end you say "running stratum" 
./build/bin/monero-stratum config.json

what command am I supposed to give?  in what folder should I be?  I'm not a big expert in Linux (to say the least).

**Comment by stoffu** [comment]
`monero-stratum` is the name of the executable located at `<repo-root-dir>/build/bin/`, so it _is_ itself the command. Just type it so in the terminal. Note that you'd need to edit config.json appropriately before running.

**Comment by Qurmo** [comment]
I must be doing something wrong then.  When I come to the point "Build stratum:" I can't really understand what commands I'm supposed to type.  both my "monero" and "monero-stratum" are locatede in my user home folder.  (at this point monero isn't build yet).

but you speak of /opt/src/.

**Comment by stoffu** [comment]
> I can't really understand what commands I'm supposed to type.

Maybe you don't have those basic development tools like `cmake` and `make` installed on your computer? Perhaps that's why you're so confused here. You need to build Monero first, because `monero-stratum` needs to link against some Monero shared libraries (which is why you need to pass `-DBUILD_SHARED_LIBS=1` to `cmake`). To build Monero, you need to install some dependencies such as Boost. Follow this instruction: https://github.com/monero-project/monero

**Comment by gradosrawk** [comment]
Hello there. I already follow al those . but wheni conpile monero its fail on 59%.

**Comment by Qurmo** [comment]
I restarted from scratch, 

the make command and cmake both work on my rig.  all seems to work fine it's when I hit
"Build stratum:

MONERO_DIR=/path/to/monero cmake .
make"

 part that it doesn't work.  Just to have things sorted out.  
my monero path is: /home/monero/
my stratum path is: /home/monero/monero-stratum/

so I should type "MONERO_DIR=/home/monero/ cmake" is that correct?

**Comment by stoffu** [comment]
Type MONERO_DIR and cmake in the same line. Or you can skip setting MONERO_DIR by putting the monero-stratum folder directly under /home/

**Comment by sammy007** [comment]
Do what @stoffu said.
