### ISSUE TITLE
Need more detail for installation

### ISSUE THREAD

**Issue by alptolga** [sammy007/monero-stratum#8]
./pool config.json
There is no pool executable to run. Please can you give more detail installation instruction? I downloaded monero linux and I run the node but I couldn't work the stratum pool.

**Comment by sammy007** [comment]
All installation info is in README. It's pretty straight forward.

**Comment by c789** [comment]
I also could not make sense of the installation. I'm on Ubuntu 16.04. Step-by-step instructions would be very much appreciated. Here's my unsuccessful interpretation:

(Put Monero source code in /opt/src/monero, then)
cd /opt/src/monero
cmake -DBUILD_SHARED_LIBS=1 .
make
sudo apt-get install golang
export GOPATH=~/go
go get github.com/yvasiyarov/gorelic

If multiple processes need to be run, it would also be helpful to provide instructions like "In terminal or pane 0, run X by executing... In terminal or pane 1, run Y by executing..." etc.

**Comment by alptolga** [comment]
I haven't too much experience on linux but I installed many things before. I checked the installing monero from source and I see that it is hard. I use the executable files which are released in monero page. Because of this it is impossible to use go cryptonote pool. I also use zcash proxy. It is more user friendly and simple.

**Comment by sammy007** [comment]
There are 2 commands for it, it's easy, and yes, zcash-proxy is easy because it's binary (run and go). This is free project, if I will find a way to make it simple I will make it simple, unfortunately it's impossible for now. Somebody can make a PR with full makefile or stupid bash script and I will apply it.

You can go with monero bins for daemon, but you must compile from source in order to go-pool to link with monero dynamic crypto libraries.

**Comment by slavserver** [comment]
wher for win64? plz

**Comment by sammy007** [comment]
I can't provide more details. If you can't install it, bypass it.
